### ISSUE TITLE
Lab 1 Clarification 

### ISSUE THREAD

**Issue by mrowland1** [Watts-College/cpp-528-spr-2022#1]
Hi @yukicruz,
Our team wanted to clarify the instructions for Lab 1. On the assignment page it says have one team member submit the Kanban board when complete. 
However, on the rubric it says "These labs should be completed and submitted individually (you are still allowed to collaborate on labs but submit your labs individually)."

So should we only have one person create this Kanban board or we all need to do so individually?

**Comment by yukicruz** [comment]
Hi @mrowland1,

Only one Kanban board for the entire team is needed. You will all use that one Kanban board to collaborate on the project. As such, your entire team does not need to send me a link to the Kanban board--I can see the history of each member's work on the Kanban and Repository histories.

Please email me next time at Yuki.Cruz@asu.edu for faster replies. I check my ASU email much more regularly than my GitHub alerts.
