### ISSUE TITLE
Lab 3 Import::Here Error

### ISSUE THREAD

**Issue by mrowland1** [Watts-College/cpp-528-spr-2022#10]
I went through all of the "Data Steps" instructions successfully but when I tried to run the 
import::here("clean_d",
             "tidy_up_data",
             "build_year",
             "RELEVANT_FILES",
             "obtain_crosswalk",
             "create_final_metadata_file",
             # notice the use of here::here() that points to the .R file
             # where all these R objects are created
             .from = here::here("data/labs/wk03/utilities.R"),
             .character_only = TRUE)

for the lab, it gave me the following error:
"Error: Cannot assign name to different value in the given environment. Name already in use."

**Comment by yukicruz** [comment]
@mrowland1, try clearing your Global Environment within RStudio then restart R.

**Comment by u12345** [comment]
@mrowland1 

Clean the variables as shown in the page, run the script again
https://www.geeksforgeeks.org/clear-the-console-and-the-environment-in-r-studio/

**Comment by mrowland1** [comment]
That didn't do anything. It says the same thing.

**Comment by yukicruz** [comment]
In addition to the directions in the [link](https://www.geeksforgeeks.org/clear-the-console-and-the-environment-in-r-studio/) that Ujitha [post](https://github.com/Watts-College/cpp-528-spr-2022/issues/10#issuecomment-1088066927)ed to clear the console and environment, you can also try clicking on: Session > Restart R and Clear Output.

Then restart RStudio and your computer for further measure.

**Comment by u12345** [comment]
@mrowland1,

Did you try to use the brush  as shown in the attached file?
[rstudio.docx](https://github.com/Watts-College/cpp-528-spr-2022/files/8420422/rstudio.docx)
