### ISSUE TITLE
Renv folder questions

### ISSUE THREAD

**Issue by krbrick** [Watts-College/cpp-528-spr-2022#12]
Is there here package supposed to be documented in 
renv/activate.r folder in github?

**Comment by krbrick** [comment]
Also are we supposed to be adjusting the utilities.r file with functions?

**Comment by yukicruz** [comment]
> Is there here package supposed to be documented in
> renv/activate.r folder in github?

The <code>here</code> package will appear locally in a directory similar (but possibly different based on your system) to this: <code>... renv >library > R-4.1 > x86... > here</code>

**Comment by yukicruz** [comment]
> Also are we supposed to be adjusting the utilities.r file with functions?

I find it cleaner to keep each .R file separate for each lab as you progress through the course. Your .R file stores your data processing steps. You do not have to call it utilities.R anymore but there's also no reason to overcomplicate a name or change a name that already works. Lab04 has a _lab_04_source.R_ file [here](https://watts-college.github.io/cpp-528-spr-2022/labs/lab-04-tutorial.html).

As you do move towards focusing on the final project, it may help to consolidate the necessary functions into a master utilities R file.
